#!/bin/bash

branch=$1
if [[ ! -z $branch ]]; then
    echo "Will git merge sub-directories for branch $branch" 
else
    echo "Will git merge sub-directories at current branch"
fi
for d in */ ; do
    echo "Changing to directory $d"
    cd "$d"
    if [ -d ".git" ]; then
        echo "Git pulling $d ..."
        git pull
        if [[ ! -z $branch ]]; then
            echo "Merging from branch $branch"
            git merge $branch
        fi
    fi
    cd ..
    echo "$d"
done
